Feature/order: 주문서 기본 UI & 토스 연동
nhnacademy-be7-2joping/2joping-front pull request #22
Opened 2024-11-07 04:16 UTC by Sauter001

## 기능
- order/form 으로 조회 가능
- 주문서 작성 UI 템플릿 작성
- toss payment 적용
  - 결제 처리는 되며 이에 따른 주문 등록 처리 필요
 
## 완성 시 구현 필요한 부분
- 회원 쿠폰 발급 가능 (`<select>`로 선택 가능하게 함)
- 장바구니 정보 조회 가능

2024-11-07 04:30 UTC, Sauter001 reviewed
추가 정보 등록

2024-11-07 04:30 UTC, Sauter001 commented on src/main/resources/templates/component/toss-widget/checkout.html
> +            const clientKey = "test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm";
- 현재 토스 위젯에 대해 개인키를 받으려면 사업자 등록 번호가 필요함 -> 공식 문서에 명시된 test client key로 대체
  - 실제 결제 처리 X

2024-11-07 04:30 UTC, Sauter001 commented on src/main/resources/templates/component/toss-widget/checkout.html
> +                });
장바구니 연동 후 실제 주문 정보로 적용 필요

2024-11-07 04:30 UTC, Sauter001 commented on src/main/java/com/nhnacademy/twojopingfront/payment/controller/PaymentController.java
> +        model.addAttribute("amount", amount);
주문 페이지 완성 시 주문 정보 보이기 위한 속성을 넣어야 할 수 있음

2024-11-07 04:30 UTC, Sauter001 commented on src/main/resources/templates/order/order-form.html
> +    <script src="https://js.tosspayments.com/v2/standard"></script>
토스가 제공하는 결제 수단 렌더링 위해 필요

2024-11-07 12:40 UTC, Ori-Gui reviewed
확인했습니다! 고생하셨습니다!!

2024-11-08 01:26 UTC, YeonWooKimm requested changes
확인입니다!

2024-11-08 01:26 UTC, YeonWooKimm approved these changes
확인입니다!

2024-11-08 03:38 UTC, merged